version: 1
name: default
description: Deny-all network policy with localhost inference access

filesystem_policy:
  read_only_root: true
  include_workdir: true
  read_write:
    - /sandbox
    - /tmp
    - /dev/null
  read_only:
    - /usr
    - /lib
    - /etc
    - /proc
    - /dev/urandom

landlock:
  compatibility: best_effort

process:
  run_as_user: sandbox
  run_as_group: sandbox

network_policies: {}
